#logging:
#  config: classpath:logback.xml

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 1000MB
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.9.151/mars?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: dengtacj@2015

mars:
  tmpUploadPath: E:\mars\tmp
  deployPath: E:\mars\install
server:
  port: 9000